version: '3.8'

services:
  postgres:
    image: postgres:12
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: 'no'

  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .development.env
    volumes:
      - ./app:/app
    ports:
      - '3000:3000'
    command: npm run start:prod
    depends_on:
      - postgres
    expose:
      - '3000'
    restart: 'no'

volumes:
  pgdata:
