version: '3.8'

services:
  postgres:
    image: postgres:12
    env_file:
      - .production.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      mode: replicated
      replicas: 4
    env_file:
      - .production.env
    volumes:
      - ./app:/app
    command: npm run start:prod
    depends_on:
      - postgres
    expose:
      - '3000'
    restart: always

  nginx-proxy:
    image: nginx
    environment:
      VIRTUAL_HOST: 'oct.local'
    ports:
      - 127.0.0.1:8080:80
      - 127.0.0.1:4443:443
    volumes:
      - './docker/nginx:/etc/nginx/conf.d'
    depends_on:
      - backend
    restart: always

volumes:
  pgdata:
