version: '3.8'

services:
  postgres:
    container_name: postgres
    image: postgres:12
    env_file:
      - .development.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - '5432:5432'
    expose:
      - '5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .development.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - '5111:5111'
    command: npm run start:prod
    depends_on:
      - postgres
    expose:
      - '5111'
    restart: always

volumes:
  pgdata:
