# name: ci

# on:
#   push:
#     branches:
#       - 'feature/ci'
# env:
#   REGISTRY: ghcr.io
#   IMAGE_NAME: ${{ github.repository }}      

# jobs:
#   build-and-push-image:
#     runs-on: ubuntu-latest
#     permissions:
#       contents: read
#       packages: write

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Login to GitHub Container Registry
#         uses: docker/login-action@v1
#         with:
#           registry: ghcr.io
#           username: ${{ github.actor }}
#           password: ${{ secrets.GITHUB_TOKEN }}

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

#       - name: Build and push Docker image
#         uses: docker/build-push-action@v2
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}        

#       - name: Deploy to Digital Ocean droplet via SSH action
#         uses: appleboy/ssh-action@v0.1.2
#         with:
#           host: ${{ secrets.SSH_HOST }}
#           username: ${{ secrets.SSH_USERNAME }}
#           key: ${{ secrets.SSH_KEY}}
#           script: |
#             docker stop $(docker ps -aq)
#             docker rm $(docker ps -aq)
#             docker rmi $(docker images -q)
#             docker login https://ghcr.io -u ${{ github.repository_owner }} -p ${{ secrets.GITHUB_TOKEN }}
#             docker pull ghcr.io/mighty-vision/otcdesk-backend:master
            
